modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "sdmloot"
version = "${version}"
displayName = "SDMLoot"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.sdmloot]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmloot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmloot]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
